feat(BV,CP): Ephemeral API for domain updates
OCamlPro/alt-ergo pull request #1055
Opened 2024-03-13 08:07 UTC by bclement-ocp

This patch adds a new ephemeral (imperative) interface to the `Domains` API, and uses it for constraint propagation. The conversion between the persistent and ephemeral APIs is provided by a function `edit` that returns an ephemeral domain (implemented using a hash table) from a persistent one, and a `snapshot` function that performs the inverse operation.

Ephemeral domains are only used internally during constraint propagation so that the external API of the `Bitv_rel` module stays persistent.

This leads to more readable code for the constraints, and should be more efficient on large problems as we do not keep looking up the domains in a `Map`.

**Note**: This depends on (and includes) #1040, #1044 and #1054; only the last commit titled "feat(BV,CP): Ephemeral API for domain updates" is new.

2024-03-18 12:01 UTC, Halbaroth requested changes

2024-03-18 12:01 UTC, Halbaroth commented on src/lib/reasoners/rel_utils.ml
> +        the first time it is created, and updated with [update]. *)
Where is the definition of the function `default`? It doesn't appear in the implementation of `handle`.

2024-03-18 12:01 UTC, Halbaroth commented on src/lib/reasoners/rel_utils.ml
> +        [domain]s. *)
In my opinion, `The type of xs` means the values of this type are the `xs`, so here I understand that `type t` is the type whose the inhabitants are single ephemeral domains. The second part of the comment is clearer by far. So  I suggest:
``` 
The type of mutable mappings of semantic values to [domain]s. 
```

2024-03-18 12:01 UTC, Halbaroth commented on src/lib/reasoners/rel_utils.ml
> +      if X.is_a_leaf r then
I know the function `X.is_a_leaf` isn't a part of this PR but I would like to discuss a bit about it. I'm not a fond of its name. 

Commonly the terminology `leaf` denotes nodes of trees without children. The name `X.is_a_leaf` sticks this naming convention (at least for non-ac symbols).

The papers about `CC(X)` defined another notion of leaves: a leaf of a semantic value `r` (relatively to a subtheory `T`) is a maximal subterm of `r` that isn't interpreted in `T`. The call `X.leaves r` returns the list of the leaves in this sense (for the theory of the top symbol of `r`).

The elements of `X.leaves` doesn't satisfy the predicate `X.is_a_leaf` in general.

We should at least mention this difference in the documentation of `X.is_a_leaf` or rename some functions. I'm not sure what is the best solution because the papers about Alt-Ergo used the second convention and keeping an implementation close to papers is a good thing.

2024-03-18 12:01 UTC, Halbaroth commented on src/lib/reasoners/rel_utils.ml
> +      if X.is_a_leaf r then
We may rename `X.leaves` to `X.aliens` for instance.

2024-03-18 12:16 UTC, bclement-ocp commented on src/lib/reasoners/rel_utils.ml
> +      if X.is_a_leaf r then
> The papers about CC(X) defined another notion of leaves: a leaf of a semantic value r (relatively to a subtheory T) is a maximal subterm of r that isn't interpreted in T. The call X.leaves r returns the list of the leaves in this sense (for the theory of the top symbol of r).
>
> The elements of X.leaves doesn't satisfy the predicate X.is_a_leaf in general.

I don't think that is true? `X.leaves` can only return uninterpreted terms and AC symbols, which is also what is tested by `is_a_leaf`. I think that this corresponds to the CC(X) definition (or rather the AC(X) definition which allows AC symbols to be leaves).

If `r` is a semantic value whose top interpreted symbol is a symbol in `T`, then the maximal subterms of `r` that is not interpreted in `T` is necessarily uninterpreted; if it was interpreted in another theory (except AC) we could not write a solver.

2024-03-18 13:16 UTC, Halbaroth commented on src/lib/reasoners/rel_utils.ml
> +      if X.is_a_leaf r then
You are right. I had a misconception about leaves in `CC(X)`. I have been fooled by this sentence in the paper about `CC(X)`:
``` 
Its role is to return the set
of maximal uninterpreted values a given semantic value consists of. Its
behaviour is left undefined, but is constrained by axioms given below.
```
Here `uninterpreted` means uninterpreted for the supertheory `X` and indeed, after checking the implementation of `Arith.leaves`, we recursively call `X.leaves` on the maximal uninterpreted values for Arith in `Arith.leaves`.

2024-03-19 09:42 UTC, bclement-ocp commented
Changes applied; ready for round 2.

2024-03-19 09:47 UTC, Halbaroth approved these changes

2024-03-20 10:36 UTC, merged