feat(BV, CP): Add propagators for bvudiv and bvurem
OCamlPro/alt-ergo pull request #1084
Opened 2024-03-29 17:32 UTC by bclement-ocp

These are interval propagators only and respect the SMT-LIB semantics
for division by 0. This requires custom operators in the `Intervals`
module that update the bounds appropriately, sincethe existing `div`
operator is undefined on `0`.

**Note**: this requires and currently includes https://github.com/OCamlPro/alt-ergo/pull/1058 and #1083  ; the commit titled "feat(BV, CP): Add propagators for bvudiv and bvurem" is new.

2024-05-07 10:40 UTC, bclement-ocp commented
Rebased on #1108

2024-06-21 14:17 UTC, Halbaroth requested changes

2024-06-21 14:17 UTC, Halbaroth commented on src/lib/reasoners/intervals.ml
> +    (* [bvudiv] is euclidean division where division by zero is -1 *)
This comment is a bit ambiguous in this module. In the bitvector theory, `-1` is clearly represented as two's complement because there is no sign on bitvector. Zarith's numbers have a sign and `-1` can be:
- the negative number represented by `11111....`
- the positive number `2^sz-1`.

Here, the image when `u2 = 0` is the interval `[2^sz-1; 2^sz-1]`.

2024-06-21 14:17 UTC, Halbaroth commented on src/lib/reasoners/intervals.ml
> +          (* [y] is always zero -> identity *)
There is no `y` here. I guess `y` denotes the variable whose the interval is `u2`.

2024-06-21 14:17 UTC, Halbaroth commented on src/lib/reasoners/intervals.ml
> +                (* x < y : bvurem is the identity *)
Same here, there is no `x` and `y`.

2024-06-21 14:17 UTC, Halbaroth commented on src/lib/reasoners/intervals.ml
> +        if ZEuclideanType.equal i2.ub ZEuclideanType.zero then
I believe we assume that `y` cannot be negative, which makes sense for the modulo. We should add a test:
```ocaml 
if ZEuclideanType.compare i2.ub ZEuclideanType.zero < 0 then 
  invalid_arg ...
```

2024-06-21 14:33 UTC, bclement-ocp reviewed
Ready for round 2

2024-06-21 14:33 UTC, bclement-ocp commented on src/lib/reasoners/intervals.ml
> +    (* [bvudiv] is euclidean division where division by zero is -1 *)
The result must be a `sz`-bit integer, so it seems fairly clear to me that `-1` means `2^sz - 1`. Clarified the comment.

2024-06-21 14:33 UTC, bclement-ocp commented on src/lib/reasoners/intervals.ml
> +        if ZEuclideanType.equal i2.ub ZEuclideanType.zero then
Indeed -- good catch, I will add such an assertion.

2024-06-21 14:33 UTC, bclement-ocp commented on src/lib/reasoners/intervals.ml
> +          (* [y] is always zero -> identity *)
Yes `x` represents the variable associated with `u1` and `y` with `u2`, I believe those were the name of the intervals in the first version of the code. Clarified.

2024-06-21 14:33 UTC, bclement-ocp commented on src/lib/reasoners/intervals.ml
> +                (* x < y : bvurem is the identity *)
Ditto

2024-06-21 15:09 UTC, Halbaroth requested changes

2024-06-21 15:09 UTC, Halbaroth commented on src/lib/reasoners/intervals.ml
> +                (* y is non-zero and smaller than x; use [0, i2.ub[ *)
I don't know what's happen... the UI is terrible and it seems the most important part of the review has been lost :/ 

So:
`y` is not necessary smaller than `x` here but still `[0, i2.ub[` is a valid interval because `x % y < y <=  i2.ub`.

2024-06-21 15:28 UTC, bclement-ocp commented on src/lib/reasoners/intervals.ml
> +                (* y is non-zero and smaller than x; use [0, i2.ub[ *)
Duh, this comment and the one above were bogus indeed — fixed

2024-06-21 15:32 UTC, Halbaroth approved these changes

2024-06-21 15:46 UTC, merged