Merge records
OCamlPro/alt-ergo pull request #1095
Opened 2024-04-19 13:27 UTC by Halbaroth

2024-10-30 13:47 UTC, Halbaroth commented
As I expected, we got regressions if we do not produce a context in the `make` function of `Adt` as we did in `Records`. Consider for instance this example (I got it from a real regression):
```smt2 
(set-logic ALL)
(declare-datatype unit ((void)))
(declare-datatype t ((box (unbox unit))))
(declare-fun f (t t) Bool)
(assert (forall ((u t) (v t)) (f u (box (unbox v)))))
(assert (not (f (box void) (box void))))
(check-sat)
```
We expect that `Alt-Ergo` outputs `unsat`. It works on `next` because `X.make` adds the extra equality `(unbox (box void)) = void`. The trigger of the first assertion is `(f u (box (unbox v)))`. First, we match `(box void)` with `(box (unbox v))`, then we try to match `(unbox v)` with `void`. Of course, we cannot match them if we only consider syntactical equality, but `Matching` allows to match terms modulo equality of the union-find. `(unbox (box void))` is in the class of `void` and can match `(unbox v)` with `v --> (box void)`. 

If you modify the input file as follows:
```smt2
(set-logic ALL)
(declare-datatype unit ((void)))
(declare-datatype t ((box (unbox unit))))
(declare-fun f (t) Bool)
(assert (forall ((v t)) (f (box (unbox v)))))
(assert (not (f (box void))))
(check-sat)
``` 
Alt-Ergo outputs `unsat` on `next` and this branch. It succeeds because after many matching rounds, it will try with variable triggers and there is one variable trigger `v` which covers all the variables of the axiom. In the previous case, it won't generate it because of `u`. So the instantiation engine produces a fresh instantiation with `v = void`.

Notice that there is specific code in `Matching` to manage another corner case of the Records theory. For instance, consider the input: 
```smt2
(set-logic ALL)
(declare-datatype t ((c (b Bool))))
(declare-fun f (t) Bool)
(declare-const x t)
(assert (forall ((y Bool)) (f (c y))))
(assert (not (f x)))
(check-sat)
```
Alt-Ergo outputs `unsat` on `next` and this branch. On next, Alt-Ergo need to match `x` with `(c y)` (it is the pattern of the axiom). Again, we need to match modulo equality. But it does not know that `x = (c (b x))`. The function `xs_modulo_records` in the module `Matching` will add the term `(c (b x))` to the list of terms equal to `x` and Alt-Ergo produces the right instance. 

I removed this code in the present branch and did not write anything to replace it but still the test passes. It works for a good reason! First of all, the ADT `x` is sent to `Adt_rel` thanks to the new function `init` in `Uf`.
Since `t` is a record, we immediately obtain a domain of size 1 for `x` and we produce a fresh boolean term `k` and the equality `x = (c k)`. Of course `(c k)` is the new representative element and we can match it against the pattern of the axiom.

2024-10-30 14:57 UTC, Halbaroth commented
In the last patch, I use the context of `Adt.make` to propagate the same equalities as we did in `Records.make`. Actually I produce these equalities as soon as the type of the term is an ADT with only one constructor, which is bit more general. 

I am running benchmarks to check if this patch removes most of the regressions. Even if it does, I would prefer a solution without using the context of `X.make`.

2024-10-30 17:26 UTC, Halbaroth commented
+55-12 on ae-format and the solver is slightly faster :)

2024-11-04 14:35 UTC, Halbaroth commented
Okay, I was not completely satisfied by the last commit. It is sad to still use the context of `X.make`. 

Another way to solve this issue consists in eliminating as earlier as possible terms of the form `(box ... (unbox u) ...)` where `box` is the unique constructor of a record type and `unbox` is one of its destructor (at the appropriate position).  Let us imagine that we have the axiom:
```
forall u : t. (P u (box (unbox u)))
```
where `P` is a undefined predicate and `t` is our record type. 

If we replace it by:
```
forall w : unit. u = box w --> (P u u)
```

Alt-Ergo should generate the trigger `(P u u)` for this axiom. If we have the term `(box unit)` in the union-find, we can match `(P (box unit) (box unit))` against `(P u u)` with `u --> (box unit)` and we can take `w --> unit`. We do not need to add the equality `(unbox (box unit)) = unit`.

Actually, I tried another transformation:
```
forall w : unit. 
let u = box w in 
(P u u)
```

It works if we disable some simplifications done in the smart constructor `Expr.mk_let` and during triggers generation but we lost other problems.

2024-11-12 13:19 UTC, Halbaroth commented
I think that this PR is now ready to review. I keep the current code with context in `X.make` even if I dislike this design because I didn't find a proper approach and I think we should merge this PR and look for a better design later.

2025-02-04 16:06 UTC, bclement-ocp requested changes
Looks good overall, but there are a few things that seem non-obvious to me that I'd like to see explained.

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/adt.ml
> +      Fmt.pf ppf "(%a %a)" X.print d.d_arg DE.Term.Const.print d.d_name
This looks like it is an AE-style printer rather than an SMT-lib style printer, not sure it should be changed.

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/adt.ml
> +    let ssx, ctx =
We should call this `rev_rs` and `rs` below to denote that they are semantic value -- `ssx` and `xxs` are not particularly readable names!

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/adt_rel.ml
>          Some (eq, E.mk_constr c xs ty)
```suggestion
        Some (eq, cons)
```

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/adt_rel.ml
> -        assert (Compat.List.is_empty ctx);
We can't keep the assertion because now we create side conditions for ADTs (when they are records), but we shold keep a comment to explain why it is OK to ignore these side conditions.

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/adt_rel.ml
> -    assert (Compat.List.is_empty ctx);
Same as above -- we should keep a comment why it is OK to ignore the second return value of `X.make`.

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/matching.ml
> -                   end
Why is this not needed for records as ADTs?

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/structures/ty.ml
> -  (* for ADTs that become records. default is "{" *)
Can't say I am sad to see this one go.

2025-02-04 16:06 UTC, bclement-ocp commented on tools/gentest.ml
> +                {acc with filters = Some ["tableaux"]}
I seem to remember the difference between Tableaux and CDCL went away when adding the field equations to the context — is it not the case?

If not, a comment should be added to the test to explain why it is failing with CDCL.

2025-02-04 16:06 UTC, bclement-ocp commented on src/lib/reasoners/adt.ml
> +      in
Can you add a comment explaining what we are doing here?

2025-02-04 16:48 UTC, Halbaroth commented on src/lib/reasoners/adt.ml
> +      Fmt.pf ppf "(%a %a)" X.print d.d_arg DE.Term.Const.print d.d_name
It is a debug message, so we can print whatever we want. In my opinion, we should avoid using different formats for debug messaged based on the input format. We could use a similar printer than Dolmen for these debug messages. This modification contradicts with my own opinion (because infix notations are more readable) ;)

2025-02-13 12:37 UTC, Halbaroth commented on src/lib/reasoners/matching.ml
> -                   end
I previously explained in this PR why this piece of code is no longer necessary. I forgot about it too and investigated it again! I'm copying my explanation here with additional details:

The specific code in Matching is there to handle a corner case of the Record theory. For instance, consider the input file:
```smt2
(set-logic ALL)
(declare-datatype t ((c (b Bool))))
(declare-fun f (t) Bool)
(declare-const x t)
(assert (forall ((y Bool)) (f (c y))))
(assert (not (f x)))
(check-sat)
```
Alt-Ergo outputs unsat on next and on this branch. On next, Alt-Ergo needs to match `x` with  `(c y)`, as it is the pattern of the first axiom. We need to match modulo equality. But it does not know that `x = (c (b x))`. This equation is only generated for record construction terms and `x` is a variable. The function `xs_modulo_records` adds the term `(c (b x))` into the class of `x` and Alt-Ergo produces the right instance.

I removed this code in the present branch and did not write anything to replace it but still the above test succeed. It works for a good reason! 
First of all, the ADT `x` is sent to `Adt_rel` thanks to the new function `init` in `Uf`.
Since `t` is a record type, we immediately obtain a domain of size 1 for `x` and we produce a fresh boolean term k and the equality `x = (c k)`. Of course `(c k)` is the new representative element and we can match it against the pattern of the axiom.

2025-02-13 15:37 UTC, Halbaroth commented on tools/gentest.ml
> +                {acc with filters = Some ["tableaux"]}
Good catch. It is a regression. The test: 
```smt2 
(set-logic ALL)the 
(declare-datatype t ((B (i Int))))
(declare-const e t)
(assert ((_ is B) e))
(assert (forall ((n Int)) (distinct e (B n))))
(check-sat)
```
succeeds on next but fails on this branch. Note that this input file is very closed to issue #1295 but `(assert ((_ is B) e)` is a ground constraint on `e`. Currently, this branch manages to discover the equality `e = (B .k)` for a fresh integer `.k` but the new term `(B .k)` never reaches the matching environment. More precisely, the new term is discarded here: 
https://github.com/OCamlPro/alt-ergo/blob/837293ef8d4c55eafdcc152089866a24db4fca91/src/lib/reasoners/satml.ml#L1084-L1099

In tableaux, all the new terms generated by relations are sent to the matching environment. 
Actually, I tried to fix this issue months ago. See https://github.com/OCamlPro/alt-ergo/commit/cca32808d8f8348728214b9d25b4ea22ff6ecaa9. The benchmarks was pretty bad (+25-195 after correction).

2025-02-14 16:57 UTC, Halbaroth commented on tools/gentest.ml
> +                {acc with filters = Some ["tableaux"]}
The test is still ignored on CDCL but I put a link to the issue #1262

2025-02-14 16:58 UTC, Halbaroth commented on src/lib/reasoners/adt_rel.ml
> -    assert (Compat.List.is_empty ctx);
I put a link to the issue #1296

2025-02-17 14:18 UTC, bclement-ocp approved these changes
I am really uneasy about losing such simple proofs as the 1008 example — we really should figure out a way to send those terms back to matching.

2025-02-17 14:18 UTC, bclement-ocp commented on src/lib/reasoners/matching.ml
> +  *)
Should be removed?

2025-02-17 14:23 UTC, Halbaroth commented
> I am really uneasy about losing such simple proofs as the 1008 example — we really should figure out a way to send those terms back to matching.

I can work on it this week, no rush to merge this PR.

2025-02-24 09:53 UTC, Halbaroth commented
Ok, this PR is quite old... I thought `1008/record.smt2` was a regression but it wasn't! Before this PR, we could prove the test with both `Tableaux` and `CDCL`. After this PR, we can prove it with `Tableaux`. The test have been introduced in this PR https://github.com/OCamlPro/alt-ergo/pull/1211 and you suggested to add it in the issue https://github.com/OCamlPro/alt-ergo/issues/1008. In #1008, you noticed that we are able to solve:
```smt2 
(set-logic ALL)
(declare-datatype t ((A) (B (i Int))))

(declare-const e t)

(assert ((_ is B) e))
(assert (forall ((n Int)) (distinct e (B n))))
(check-sat)
``` 
which means that the issue with `1008/record.smt2` is not related with #1262 as I thought. I remove the link to #1262 and merge this PR as it does not introduce regressions.

2025-02-24 10:13 UTC, merged