feat(BV): Add support for bv2nat/int2bv normal forms
OCamlPro/alt-ergo pull request #1154
Opened 2024-07-01 10:13 UTC by bclement-ocp

Currently, Alt-Ergo knows the value of [bv2nat] and [int2bv] on
constants. We also perform some simplifications during semantic value
creation; however, these simplifications are not integrated into the
rest of the solver. For instance, we know that [bv2nat(x @ y)] is equal
to [bv2nat(x) * 2^n + bv2nat(y)] (where [n] is the bit-width of [y]),
but we don't know that [z] is equal to the same under the hypothesis
that [z = x @ y].

This patch moves these simplifications to the [Bitv_rel] module, making
them an integral part of the solving process. Since we can't compute
[bv2nat] (or [int2bv]) of an arbitrary semantic value, we generate fresh
variables to represent them when needed.

Note: this PR depends on #1144 and #1152. Only the last commit titled "feat(BV): Add support for bv2nat/int2bv normal forms" is included in this PR.

2024-07-11 07:38 UTC, bclement-ocp commented
Fixes #824 

(I don't know why it does not appear in the "Development" dropdown...)

2024-08-06 07:49 UTC, Halbaroth commented
I'm ready to review this PR as soon as you rebase it ;)

2024-08-06 07:51 UTC, bclement-ocp commented
@Halbaroth done!

2024-08-18 12:08 UTC, Halbaroth requested changes

2024-08-18 12:08 UTC, Halbaroth commented on tests/bitv/testfile-bv2nat-007.smt2
> +(assert (distinct (mod (- x y) 179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424
We may use the pow function here? Or you want to respect the SMT-LIB2 standard?

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +    end
We may move these helper functions to `Polynomial` in a notation module?

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +        in [nat2bv]. *)
```suggestion
        We maintain the invariant that if [(bv, ext)] is associated with
        [(p, ex)] in this map, then [p] is associated with [(bv, ext, ex)]
        in [nat2bv]. *)
```

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs], or raises
```suggestion
  (* Returns the polynomial associated with [bv2nat(bv asr ofs)], or raises
```

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs], creating a
```suggestion
  (* Returns the polynomial associated with [bv2nat(bv asr ofs)], creating a
```

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs], or raises
Note that it is not very important because we can define the usual operator `lasr` on integers as: `x lasr ofs = bv2nat(nat2bv(x) asr ofs)` but it is better to be consistent with our notations and we use `asr` on bitvectors in other comments.

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs].
```suggestion
  (* Returns the polynomial associated with [bv2nat(bv asr ofs)].
```

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +    in
I think it is a bit clearer to factorize these two exception handlers as follows:
```ocaml 
try 
   let bv', ext', ex' = T.Ints.Map.find p t.nat2bv in 
   ...
   let p', ex' = find_ext bv ext t.bv2nat in 
   ...
   false, t
with Not_found -> true, t
```

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +     If we know that [int_r] is an exact bit-vector representation (i.e. [int_r]
```suggestion
     If we know that [int_r] has an exact bit-vector representation (i.e. [int_r]
```

2024-08-18 12:08 UTC, Halbaroth commented on src/lib/reasoners/bitv_rel.ml
> +        [subst]. *)
Can you justify this design please?

2024-08-19 09:00 UTC, bclement-ocp commented on tests/bitv/testfile-bv2nat-007.smt2
> +(assert (distinct (mod (- x y) 179769313486231590772930519078902473361797697894230657273430081157732675805500963132708477322407536021120113879871393357658789768814416622492847430639474124377767893424
I'd prefer keeping the SMT2 tests as compliant as possible. I don't think it is an issue to have a huge constant in a test.

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +     If we know that [int_r] is an exact bit-vector representation (i.e. [int_r]
Done.

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +    in
I am always very wary when seeing calls to `find` functions that are not immediately within an exception handler because it is very easy to introduce subtle bugs this way.

In fact, the code you suggest has one such subtle bug: when adding the relation between `p` and `ext`, both `p` and `ext` might already have a recorded integer/bit-vector counterpart independently. If `T.Ints.Map.find p t.nat2bv` raises `Not_found` but `find_ext bv ext t.bv2nat` does not, we must return `false` and remove the existing mapping for `ext`, but your suggested code returns `true` and an unmodified `t`.

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs].
Done

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs], creating a
Done

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +  (* Returns the polynomial associated with [bv2nat(bv) asr ofs], or raises
It actually matters because `asr` on bit-vectors is truncated whereas on integers it is not!

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +        [subst]. *)
It creates less variables. Instead of having $O(n^2)$ possible variables for each extraction, we only have $O(n)$ possible variables for each shift.

It also means the arithmetic theory knows equalities such as `x<2, 5> - x<2, 3> = 4 * x<4, 5>` by normalization, which is nice, but really the motivation is to use less variables.

I updated the comment to explain this.

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +        in [nat2bv]. *)
Fixed, and also clarified what "associated with" means here to clarify which is the key and which is the value.

2024-08-19 09:00 UTC, bclement-ocp commented on src/lib/reasoners/bitv_rel.ml
> +    end
Not the `mkv_eq` and `mkv_le` helpers, but otherwise yes. Done (although I did not use a notation module, following the usual convention e.g. in Zarith that operators are defined directly in the corresponding module, unlike syntax extensions such as `let*`).

2024-08-20 09:54 UTC, Halbaroth approved these changes

2024-08-20 09:55 UTC, merged