feat(BV, Opt): Support bit-vector optimization
OCamlPro/alt-ergo pull request #1165
Opened 2024-07-16 12:49 UTC by bclement-ocp

Since we track intervals for bit-vector variables, adding support for optimization in the bit-vector theory is fairly inconsequential.

Fixes #884

2024-07-16 17:03 UTC, Halbaroth requested changes

2024-07-16 17:03 UTC, Halbaroth commented on tests/models/bitv/optim-4.models.smt2
> +(assert (P (bvabs32 x)))
We can remove these lines after merging #1166.

2024-07-16 17:03 UTC, Halbaroth commented on src/lib/structures/expr.mli
> +  val of_Z : size:int -> Z.t -> t
We expose this function that raises an assertion if `size <= 0`. We should raise `invalid_arg` instead.

2024-07-17 10:03 UTC, Halbaroth approved these changes
Great :) 

You just need to push new expected files.

2024-07-17 10:24 UTC, bclement-ocp commented
I did, but looks like I messed up a newline by editing the file directly. Fixed.

2024-07-17 10:29 UTC, merged