Fix issue 482
OCamlPro/alt-ergo pull request #489
Opened 2021-10-22 11:00 UTC by hra687261

Purification of functional array expressions, fixes issue #482.

2021-10-22 11:40 UTC, Gbury requested changes
I tihk the fix is good, but I left a few comments. Also, while we're at it, could you change the `assert false` that are present in the purification functions into e.g. `failwith "unexpected expression in purification function"` so that the error message is less cryptic when such bugs occur again ?

2021-10-22 11:40 UTC, Gbury commented on src/lib/structures/expr.ml
> +          | [x; y] ->
Please give more informative names to these variables. For instance, to better distinguish which is the expression for the array, and which is the expression for the looked-up index.

2021-10-22 11:40 UTC, Gbury commented on src/lib/structures/expr.ml
> +                mk_lifted x' lets
wouldn't it be better to lift the required let-bindings at the top ? i.e. something like: `let x', x'_lets = .... in let y', y'_lets = ... in mk_lifted ...` ?

2021-10-22 12:54 UTC, hra687261 commented on src/lib/structures/expr.ml
> +          | [x; y] ->
Ok, I replaced ```x``` with ```fa``` for functional array, and ```y``` with ```i``` for index.

2021-10-22 12:56 UTC, hra687261 commented on src/lib/structures/expr.ml
> +                mk_lifted x' lets
Yes, you're right. It's done.

2022-04-07 11:45 UTC, Gbury approved these changes

2022-04-07 12:15 UTC, merged