Support zip format with Dolmen frontend
OCamlPro/alt-ergo pull request #545
Opened 2023-01-18 09:47 UTC by Halbaroth

This PR adds the support for the zip format while using the Dolmen frontend.

2023-01-18 21:00 UTC, hra687261 commented
LGTM, the couple of comments I made are really more a matter of taste than anything, so I leave them to your discretion :) 
Edit: Other than the issue related to parsing AE files non-incrementally, but from what I understand, this is a dolmen issue, not an Alt-Ergo one.

2023-01-19 08:44 UTC, Halbaroth commented
This PR is not ready for review ;) Dolmen reads raw input in incremental mode but this mode is not available in AE native language. I am adding the full mode for raw input in Dolmen.

2023-02-01 16:14 UTC, Halbaroth commented
This PR should be ready to merge on next as soon as the last release of Dolmen is available on opam: https://github.com/ocaml/opam-repository/pull/23213

2023-02-15 17:15 UTC, Halbaroth commented
Is it fine for you @hra687261 ?

2023-02-15 20:07 UTC, hra687261 requested changes
~~Edit: nvm, LGTM!~~

2023-02-15 20:07 UTC, hra687261 commented on src/bin/common/solving_loop.ml
> +        In_channel.close cin;
The whole `In_channel` module was added in 4.14.0. You can use `close_in` from the stdlib.

2023-02-15 20:10 UTC, hra687261 approved these changes

2023-02-15 20:42 UTC, hra687261 requested changes
Sorry, one final change!

2023-02-15 20:42 UTC, hra687261 commented on dune-project
> +  (dolmen_loop (>= 0.8.1))
You should remove `(camlzip (>= 1.07))` from `alt-ergo-parsers` and add it to `alt-ergo-lib` since the calls to `camlzip` were moved to the library.

2023-02-16 08:32 UTC, Halbaroth commented
@hra687261 I am ready to merge 😊

2023-02-16 08:32 UTC, hra687261 commented
Perfect @Halbaroth go ahead!

2023-02-16 08:34 UTC, Halbaroth commented
I cannot until you accept my changes 😅

2023-02-16 08:36 UTC, hra687261 approved these changes

2023-02-16 08:36 UTC, merged

2023-02-16 08:37 UTC, hra687261 commented
I was on the mobile app and didn't find where to approve the changes lol