Support for the check_sat statement in Dolmen frontend
OCamlPro/alt-ergo pull request #594
Opened 2023-04-24 05:55 UTC by Halbaroth

The model PR add a new statement in the native language that is not present in Dolmen.

2023-04-24 07:57 UTC, bclement-ocp commented
This doesn't seem to work?

```
6 | check_sat g :
                ^
Error Syntax error (state 336) while reading the reserved word ':'.
```

2023-04-24 08:12 UTC, Halbaroth commented
You have to use my PR on dolmen also.

2023-04-24 09:57 UTC, bclement-ocp commented
Ah, would have been good to mention. Gbury/dolmen#140

Looking at the code for the `Solve` case smtlib (below in `solving_loop`) it looks like we maybe should merge back the two cases if we have support for `Solve` in `D_cnf`?

2023-04-25 13:21 UTC, Halbaroth commented
I applied the modifications :)

2023-06-09 09:16 UTC, bclement-ocp commented
Is this compatible with the last changes to Gbury/dolmen#140? If so, please resolve the conflicts and I will take a look.

2023-06-13 10:54 UTC, bclement-ocp commented
@Halbaroth Can you please resolve the conflicts with the `next` branch so that I can take a look? Thanks.

2023-06-13 16:50 UTC, Halbaroth commented
It's ready :)

2023-06-14 07:10 UTC, bclement-ocp requested changes
Looks good to me with some minor changes, I'd say let's wait on #630 to make them and merge however.

2023-06-14 07:10 UTC, bclement-ocp commented on docs/sphinx_docs/Input_file_formats/Native/04_setting_goals.md
> -This keyword is an alias for `goal`.
RIP

2023-06-14 07:10 UTC, bclement-ocp commented on src/bin/common/solving_loop.ml
> +              | _ -> assert false
I don't think this case is needed, OCaml should be able to infer that `contents` has type ``[ `Solve of _ list * _ list ]`` (there is no "this match case is unused" because with the match it gets inferred as ``[> `Solve of _list * _list]`` instead, it is a known limitation of polymorphic variants).

2023-06-14 07:10 UTC, bclement-ocp commented on src/bin/common/solving_loop.ml
> +              | `Solve _ -> failwith "not yet supported"
```suggestion
              | `Solve _ -> failwith "Only `(check-sat)` with no arguments is supported."
```

2023-06-14 07:10 UTC, bclement-ocp commented on src/bin/common/solving_loop.ml
> +                  `Solve ([], [DStd.Expr.Term.(of_cst Const._false)])
I am not a very big fan of passing the general form of `` `Solve `` to `D_cnf.make`, and then have `D_cnf.make` ignore some of the solves.

I think it would be better to keep `` `Goal` in `D_cnf.make` (see what I did in #630 ) and have a new constructor (maybe `` `Check``?) for the check-sat case.

2023-06-15 09:47 UTC, Halbaroth commented on docs/sphinx_docs/Input_file_formats/Native/04_setting_goals.md
> -This keyword is an alias for `goal`.
We remove check_valid right?

2023-06-15 09:48 UTC, bclement-ocp commented on docs/sphinx_docs/Input_file_formats/Native/04_setting_goals.md
> -This keyword is an alias for `goal`.
Yes! RIP = Requiescat In Pasce, I was semi-humorously paying respect to its short life :)

2023-06-15 09:57 UTC, Halbaroth commented on docs/sphinx_docs/Input_file_formats/Native/04_setting_goals.md
> -This keyword is an alias for `goal`.
:D very short! I know what RIP means by the way XD

2023-06-19 07:13 UTC, bclement-ocp commented
These changes are included in #652 so closing in favor of #652

2023-06-19 07:13 UTC, closed without merging