Temporary fix of issue 744
OCamlPro/alt-ergo pull request #747
Opened 2023-07-24 15:34 UTC by Halbaroth

This PR displays an appropriate error message when an ill-typed is produced by the Dolmen frontend.
The issue has been fixed on the master branch of Dolmen. Thus, this fix will be reverted when the next release of Dolmen will be released.

2023-07-24 15:52 UTC, bclement-ocp requested changes

2023-07-24 15:52 UTC, bclement-ocp commented on src/lib/frontend/d_cnf.ml
> +                 Dolmen has been released. *)
Please make an AE issue for this and reference it here.

2023-07-25 08:25 UTC, Halbaroth commented
Is it ok?

2023-07-25 08:38 UTC, bclement-ocp commented
Plase add a link to #748 in the comment.

2023-07-25 09:07 UTC, bclement-ocp approved these changes

2023-07-25 11:26 UTC, merged